# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creative', '__first__'),
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=16, verbose_name='Code')),
                ('category', models.IntegerField(choices=[(1, 'Wash'), (2, 'Bleach'), (3, 'Dry'), (4, 'Wring'), (5, 'Iron'), (6, 'Dry Clean')], default=0, verbose_name='Category')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('icon_height', models.IntegerField(default=0, verbose_name='Icon Height')),
                ('icon_width', models.IntegerField(default=0, verbose_name='Icon Width')),
                ('icon', models.ImageField(blank=True, height_field='icon_height', null=True, upload_to='', width_field='icon_width')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Care Components',
                'verbose_name': 'Care Component',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareInstructions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('icon_bleach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_bleach', to='app_care.CareComponent', verbose_name='Bleach Instructions')),
                ('icon_dry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_dry', to='app_care.CareComponent', verbose_name='Drying Instructions')),
                ('icon_dryclean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_dryclean', to='app_care.CareComponent', verbose_name='Dry Cleaning Instructions')),
                ('icon_iron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_iron', to='app_care.CareComponent', verbose_name='Ironing Instructions')),
                ('icon_wash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_wash', to='app_care.CareComponent', verbose_name='Washing Instructions')),
                ('icon_wring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_wring', to='app_care.CareComponent', verbose_name='Wringing Instructions')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
            ],
            options={
                'verbose_name_plural': 'Care Instructions',
                'verbose_name': 'Care Instructions',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='CareLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Artwork')),
                ('instructions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_care.CareInstructions')),
                ('saleschannel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.SalesChannel')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Size')),
            ],
            options={
                'verbose_name_plural': 'Care Label',
                'verbose_name': 'Care Label',
                'ordering': ['name', 'code'],
            },
        ),
    ]
