# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carelabel',
            options={'ordering': ['saleschannel', 'instructions', 'size'], 'verbose_name': 'Care Label', 'verbose_name_plural': 'Care Label'},
        ),
        migrations.RemoveField(
            model_name='carelabel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='carelabel',
            name='name',
        ),
    ]
