# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_auto_20161111_1932'),
        ('creative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.Creative', verbose_name='Creative')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='Item')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'verbose_name': 'Product',
                'ordering': ['name', 'code'],
            },
        ),
    ]
