# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0002_auto_20161117_1014'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creative',
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.Design', verbose_name='Design'),
        ),
    ]
