# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0001_initial'),
        ('product', '0002_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.SalesChannel'),
        ),
    ]
