# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0001_initial'),
        ('product', '0003_variant_sales_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='sales_channel',
        ),
        migrations.AddField(
            model_name='product',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.SalesChannel', verbose_name='Sales Channel'),
        ),
    ]
