# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bzBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzCreativeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzBrand')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzCreativeDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativecollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzCreativeLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativecollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzCreativeRendering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bzcreativedesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign')),
                ('bzcreativelayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeLayout')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=32, verbose_name='Status')),
                ('bzDesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='bzProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('bzproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzProduct')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Color')),
                ('label_clean', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Clean Label')),
                ('hex_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Color Hex Code')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogFileSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Name')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Note')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('width_in', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Width (in)')),
                ('height_in', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Height (in)')),
                ('ratio', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Ratio')),
                ('colorsystem', models.CharField(choices=[('R', 'RGB'), ('Y', 'CMYK')], default='R', max_length=1, verbose_name='Color System')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogFileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Printful ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('additional_price', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Additional Price')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogOptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Printful ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Type')),
                ('additional_price', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Additional Price')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('pid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Printful ID')),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Type')),
                ('brand', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Model')),
                ('image', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image')),
                ('variant_count', models.IntegerField(default=0, verbose_name='Variants')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Size')),
                ('label_clean', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Clean Label')),
                ('sort_group', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Sort Group')),
                ('sort_order', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Sort Order')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCatalogVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='', verbose_name='Is Active?')),
                ('pid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Printful ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('image', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image')),
                ('price', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Price')),
                ('in_stock', models.BooleanField(default=False, verbose_name='In Stock')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Weight (oz)')),
                ('pfsize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogSize', verbose_name='Size')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfPrintFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField(default=0, verbose_name='Printful ID')),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Type')),
                ('hash', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hash')),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='URL')),
                ('filename', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Filename')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MIME Type')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('dpi', models.IntegerField(default=0, verbose_name='DPI')),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Status')),
                ('created', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Created')),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Thumbnail URL')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='pfState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('pfcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfCountry', verbose_name='Country')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Website')),
                ('created', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Created')),
                ('consumer_key', models.CharField(blank=True, default='', max_length=64, verbose_name='API Consumer Key')),
                ('consumer_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='API Consumer Secret')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='pfSyncItemOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Printful ID')),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Value')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfSyncProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Printful ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='External ID')),
                ('variants', models.IntegerField(default=0, verbose_name='Variant Count')),
                ('synced', models.IntegerField(default=0, verbose_name='Synced')),
                ('pfstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfStore', verbose_name='Store')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='pfSyncVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Printful ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='External ID')),
                ('synced', models.BooleanField(default=False, verbose_name='Synced')),
                ('files', models.ManyToManyField(blank=True, to='business.pfPrintFile')),
                ('pfsyncproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfSyncProduct', verbose_name='Sync Product')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('type', models.CharField(blank=True, choices=[('text', 'Basic Text'), ('color picker', 'Color Picker'), ('image select', 'Image Select'), ('text label', 'Text Label')], default='', max_length=255, null=True, verbose_name='Type')),
                ('has_archives', models.BooleanField(default=False, verbose_name='Has Archives?')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.IntegerField(blank=True, default=0, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('parent', models.IntegerField(default=0, verbose_name='Parent ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('display', models.CharField(choices=[('default', 'Default'), ('products', 'Products'), ('subcategories', 'Subcategories'), ('both', 'Display Both')], default='default', max_length=255, verbose_name='Display')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('image_id', models.IntegerField(default=0, verbose_name='Image ID')),
                ('image_date_created', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Created')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.CharField(blank=True, default='', help_text='Image ID (attachment ID). In write-mode used to attach pre-existing images.', max_length=16, null=True, verbose_name='Woo ID')),
                ('date_created', models.DateField(blank=True, help_text='READONLY. The date the product was created, in the site\x19s timezone.', null=True, verbose_name='Date Created')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alt')),
                ('position', models.IntegerField(default=0, help_text='Image position. 0 means that the image is featured.', verbose_name='Position')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('permalink', models.URLField(blank=True, verbose_name='Permalink')),
                ('date_created', models.DateField(blank=True, help_text='READONLY. The date the product was created, in the site\x19s timezone.', null=True, verbose_name='Date Created')),
                ('dimension_length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length')),
                ('dimension_width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Width')),
                ('dimension_height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Product weight in decimal format.', max_digits=10, verbose_name='Weight')),
                ('reviews_allowed', models.BooleanField(default=True, help_text='Allow reviews. Default is true.', verbose_name='Reviewed Allowed?')),
                ('images', models.ManyToManyField(blank=True, to='business.wooImage', verbose_name='Images')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooShippingClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wid', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', help_text='Generally, a two-character uppercase code. Used in SKUs.', max_length=16, null=True, verbose_name='Code')),
                ('base_url', models.URLField(blank=True, default='', help_text="Include the schema and FQDN only (e.g., 'https://example.com'). No trailing slash.", null=True, verbose_name='Base URL')),
                ('consumer_secret', models.CharField(blank=True, max_length=43, null=True, verbose_name='Consumer Secret')),
                ('timezone', timezone_field.fields.TimeZoneField(default='America/New_York')),
                ('verify_ssl', models.BooleanField(default=True, help_text='Uncheck this if you are using a self-signed SSL certificate to disable ssl verification.', verbose_name='Verify SSL?')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.IntegerField(default=0, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooStore')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('menu_order', models.IntegerField(default=0, verbose_name='Menu Order')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('wr_tooltip', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='WR Tooltip')),
                ('wr_label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='WR Label')),
                ('productattribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooAttribute', verbose_name='Product Attribute')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wooVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID')),
                ('date_created', models.DateField(blank=True, help_text='READONLY. The date the product was created, in the site\x19s timezone.', null=True, verbose_name='Date Created')),
                ('permalink', models.URLField(blank=True, verbose_name='Permalink')),
                ('sku', models.CharField(blank=True, default='', help_text='Unique identifier.', max_length=255, null=True, verbose_name='SKU')),
                ('price', models.CharField(blank=True, default='', help_text='READONLY. Current product price. This is set from regular_price and sale_price.', max_length=255, null=True, verbose_name='Price')),
                ('dimension_length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length')),
                ('dimension_width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Width')),
                ('dimension_height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Product weight in decimal format.', max_digits=10, verbose_name='Weight')),
                ('images', models.ManyToManyField(blank=True, to='business.wooImage', verbose_name='Images')),
                ('shipping_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooShippingClass')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wpMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alternate Text')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('file', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='File')),
                ('author', models.IntegerField(default=0, verbose_name='Author')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MIME Type')),
                ('comment_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=255, verbose_name='Comment Status')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('template', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Template')),
                ('ping_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=255, verbose_name='Ping Status')),
                ('caption', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Caption')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Link')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified')),
                ('guid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='GUID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('modified_gmt', models.DateTimeField(blank=True, null=True, verbose_name='Modified GMT')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('date_gmt', models.DateTimeField(blank=True, null=True, verbose_name='Date GMT')),
                ('type', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Type')),
                ('woostore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooStore')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='wpMediaSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('file', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='File')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MIME Type')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('source_url', models.URLField(blank=True, default='', null=True, verbose_name='Source URL')),
                ('wpmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.wpMedia', verbose_name='Media')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='wooproduct',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooShippingClass'),
        ),
        migrations.AddField(
            model_name='wooproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, to='business.wooTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='wooproduct',
            name='woostore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooStore', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='woocategory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooStore'),
        ),
        migrations.AddField(
            model_name='wooattribute',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooStore'),
        ),
        migrations.AddField(
            model_name='pfsyncitemoption',
            name='pfsyncvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfSyncVariant'),
        ),
        migrations.AddField(
            model_name='pfprintfile',
            name='pfstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfStore'),
        ),
        migrations.AddField(
            model_name='pfcatalogoptiontype',
            name='pfcatalogvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogVariant'),
        ),
        migrations.AddField(
            model_name='pfcatalogfiletype',
            name='pfcatalogvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogVariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='pfcatalogvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogVariant'),
        ),
        migrations.AddField(
            model_name='bzbrand',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfStore'),
        ),
    ]
