# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfcountry',
            options={'ordering': ('code',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='pfstate',
            options={'ordering': ('pfcountry__code', 'code'), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='bzLayout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeLayout', verbose_name='Layout'),
        ),
    ]
