# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woostore',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Consumer Key'),
        ),
        migrations.AlterField(
            model_name='woostore',
            name='consumer_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Consumer Secret'),
        ),
    ]
