# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170303_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzbrand',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfStore'),
        ),
        migrations.AlterField(
            model_name='pfcatalogvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='Is Active?'),
        ),
    ]
