# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170308_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='pfAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Company')),
                ('address1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='City')),
                ('zip', models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Postal Code')),
                ('phone', models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCountry', verbose_name='Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfState', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ('name',),
                'verbose_name': 'Address',
            },
        ),
        migrations.AddField(
            model_name='pfstore',
            name='packingslip_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Packing Slip Email'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='packingslip_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Packing Slip Message'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='packingslip_phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Packing Slip Phone'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='payment_expires',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Payment Card Type'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='payment_number_mask',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Payment Card Type'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Payment Card Type'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress', to='business.pfAddress', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='pfstore',
            name='return_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnaddress', to='business.pfAddress', verbose_name='Return Address'),
        ),
    ]
