# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170309_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='pfCatalogBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Catalog Brand',
                'ordering': ('-pk',),
                'verbose_name_plural': 'Catalog Brands',
            },
        ),
        migrations.CreateModel(
            name='pfCatalogType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Catalog Product Type',
                'ordering': ('-pk',),
                'verbose_name_plural': 'Catalog Product Types',
            },
        ),
        migrations.RemoveField(
            model_name='pfcatalogproduct',
            name='type',
        ),
        migrations.AlterField(
            model_name='pfcatalogproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogBrand'),
        ),
        migrations.AddField(
            model_name='pfcatalogproduct',
            name='ptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogType'),
        ),
    ]
