# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170308_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfstore',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='Printful ID'),
        ),
    ]
