# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170309_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfcatalogcolor',
            old_name='label',
            new_name='name',
        ),
    ]
