# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170303_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcatalogvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='Is Active?'),
        ),
    ]
