# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20170311_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfcatalogproduct',
            options={'ordering': ('brand', 'model'), 'verbose_name': 'Printful Product', 'verbose_name_plural': 'Printful Products'},
        ),
        migrations.AddField(
            model_name='pfcatalogvariant',
            name='pfcatalogproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogProduct', verbose_name='Catalog Product'),
        ),
        migrations.AddField(
            model_name='pfcatalogvariant',
            name='pfcolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogColor', verbose_name='Color'),
        ),
    ]
