# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170312_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='business.pfCatalogColor', verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='business.pfCatalogSize', verbose_name='Sizes'),
        ),
    ]
