# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20170303_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bzbrand',
            options={'ordering': ('code',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='bzcreativecollection',
            options={'ordering': ('code',), 'verbose_name': 'Creative Collection', 'verbose_name_plural': 'Creative Collections'},
        ),
        migrations.AlterModelOptions(
            name='bzcreativedesign',
            options={'ordering': ('bzcreativecollection__code', 'code'), 'verbose_name': 'Creative Design', 'verbose_name_plural': 'Creative Designs'},
        ),
        migrations.AlterModelOptions(
            name='bzcreativelayout',
            options={'ordering': ('bzcreativecollection__code', 'code'), 'verbose_name': 'Creative Layout', 'verbose_name_plural': 'Creative Layouts'},
        ),
        migrations.AlterModelOptions(
            name='bzcreativerendering',
            options={'ordering': ('bzcreativedesign__code', 'bzcreativelayout__code'), 'verbose_name': 'Creative Rendering', 'verbose_name_plural': 'Creative Renderings'},
        ),
        migrations.AlterModelOptions(
            name='bzproduct',
            options={'ordering': ('code',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='bzproductvariant',
            options={'ordering': ('bzproduct', 'pfsize', 'pfcolor'), 'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='pfProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogProduct', verbose_name='Vendor Product'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='pfSyncProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfSyncProduct', verbose_name='Sync Product'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='wooProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.wooProduct', verbose_name='Outlet Product'),
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='pfcolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogColor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='pfsize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogSize', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bzcreativecollection',
            name='bzbrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzBrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='bzcreativedesign',
            name='bzcreativecollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='bzcreativelayout',
            name='bzcreativecollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='bzcreativerendering',
            name='bzcreativedesign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='bzcreativerendering',
            name='bzcreativelayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeLayout', verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='bzproduct',
            name='bzDesign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='bzproductvariant',
            name='bzproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzProduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bzproductvariant',
            name='pfcatalogvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogVariant', verbose_name='Vendor Variant'),
        ),
    ]
