# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20170315_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'MIME Type',
                'ordering': ('name',),
                'verbose_name_plural': 'MIME Types',
            },
        ),
        migrations.CreateModel(
            name='pfFileStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'File Status',
                'ordering': ('name',),
                'verbose_name_plural': 'File Statuses',
            },
        ),
        migrations.CreateModel(
            name='pfFileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'File Type',
                'ordering': ('name',),
                'verbose_name_plural': 'File Types',
            },
        ),
        migrations.AddField(
            model_name='pfprintfile',
            name='filespec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfCatalogFileSpec', verbose_name='File Spec'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='mime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.MimeType', verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='pfstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pfStore', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='ptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfFileType', verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.pfFileStatus', verbose_name='File Status'),
        ),
    ]
