# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20170315_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mimetype',
            options={'ordering': ('clean_name', 'name'), 'verbose_name': 'MIME Type', 'verbose_name_plural': 'MIME Types'},
        ),
        migrations.AlterModelOptions(
            name='pffilestatus',
            options={'ordering': ('clean_name', 'name'), 'verbose_name': 'File Status', 'verbose_name_plural': 'File Statuses'},
        ),
        migrations.AlterModelOptions(
            name='pffiletype',
            options={'ordering': ('clean_name', 'name'), 'verbose_name': 'File Type', 'verbose_name_plural': 'File Types'},
        ),
        migrations.AddField(
            model_name='mimetype',
            name='clean_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pffilestatus',
            name='clean_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pffiletype',
            name='clean_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
