# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_printful', '0001_initial'),
        ('outlet_woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bzBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooStore', verbose_name='Outlet')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfStore', verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'verbose_name': 'Brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='bzCreativeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzbrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzBrand', verbose_name='Brand')),
            ],
            options={
                'verbose_name_plural': 'Creative Collections',
                'verbose_name': 'Creative Collection',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='bzCreativeDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativecollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Creative Collection')),
            ],
            options={
                'verbose_name_plural': 'Creative Designs',
                'verbose_name': 'Creative Design',
                'ordering': ['bzcreativecollection__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='bzCreativeLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativecollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Creative Collection')),
            ],
            options={
                'verbose_name_plural': 'Creative Layouts',
                'verbose_name': 'Creative Layout',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='bzCreativeRendering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bzcreativedesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Design')),
                ('bzcreativelayout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.bzCreativeLayout', verbose_name='Layout')),
                ('pfcatalogfilespec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_printful.pfCatalogFileSpec', verbose_name='Spec')),
                ('pfprintfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_printful.pfPrintFile', verbose_name='Print File')),
            ],
            options={
                'verbose_name_plural': 'Creative Renderings',
                'verbose_name': 'Creative Rendering',
            },
        ),
        migrations.CreateModel(
            name='bzProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzDesign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Creative Design')),
                ('bzLayout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeLayout', verbose_name='Creative Layout')),
                ('pfColors', models.ManyToManyField(blank=True, to='vendor_printful.pfCatalogColor', verbose_name='Colors')),
                ('pfProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogProduct', verbose_name='Printful Product')),
                ('pfSizes', models.ManyToManyField(blank=True, to='vendor_printful.pfCatalogSize', verbose_name='Sizes')),
                ('wcProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooProduct', verbose_name='Woo Product')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='bzProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('bzproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzProduct', verbose_name='Product')),
                ('pfcatalogvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogVariant', verbose_name='Printful Variant')),
            ],
            options={
                'verbose_name_plural': 'Product Variants',
                'verbose_name': 'Product Variant',
                'ordering': ['code'],
            },
        ),
    ]
