# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bzCreativeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Creative Collection',
                'verbose_name_plural': 'Creative Collections',
            },
        ),
        migrations.CreateModel(
            name='bzCreativeDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativecollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Creative Collection')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Creative Design',
                'verbose_name_plural': 'Creative Designs',
            },
        ),
        migrations.CreateModel(
            name='bzCreativeLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('bzcreativedesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Creative Design')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Creative Design',
                'verbose_name_plural': 'Creative Designs',
            },
        ),
    ]
