# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=32, verbose_name='Status'),
        ),
    ]
