# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_bzcreativecollection_bzcreativedesign_bzcreativelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzcreativecollection',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Code'),
        ),
    ]
