# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170212_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzcreativelayout',
            name='bzcreativecollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeCollection', verbose_name='Creative Collection'),
        ),
    ]
