# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170212_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzcreativecollection',
            name='bzbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzBrand', verbose_name='Brand'),
        ),
    ]
