# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_bzcreativerendering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bzcreativerendering',
            options={'verbose_name': 'Creative Rendering', 'verbose_name_plural': 'Creative Renderings'},
        ),
        migrations.AlterField(
            model_name='bzcreativerendering',
            name='pfcatalogfilespec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogFileSpec', verbose_name='Spec'),
        ),
    ]
