# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20170212_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='bzProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Products',
            },
        ),
    ]
