# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0021_auto_20170212_1759'),
        ('outlet_woocommerce', '0012_auto_20170213_2003'),
        ('business', '0010_bzproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproduct',
            name='bzDesign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeDesign', verbose_name='Creative Design'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='bzLayout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.bzCreativeLayout', verbose_name='Creative Layout'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='pfProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogProduct', verbose_name='Printful Product'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='wcProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooProduct', verbose_name='Woo Product'),
        ),
    ]
