# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0021_auto_20170212_1759'),
        ('business', '0012_bzproduct_pfvariants'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproduct',
            name='pfColors',
            field=models.ManyToManyField(blank=True, to='vendor_printful.pfCatalogColor', verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='pfSizes',
            field=models.ManyToManyField(blank=True, to='vendor_printful.pfCatalogSize', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='bzproduct',
            name='pfVariants',
            field=models.ManyToManyField(blank=True, to='vendor_printful.pfCatalogVariant', verbose_name='Variants'),
        ),
    ]
