# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20170213_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bzproduct',
            name='pfVariants',
        ),
    ]
