# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0022_auto_20170214_0035'),
        ('business', '0014_remove_bzproduct_pfvariants'),
    ]

    operations = [
        migrations.CreateModel(
            name='bzProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('bzproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzProduct')),
                ('pfcatalogvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogVariant')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['code'],
            },
        ),
    ]
