# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_bzproductvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproductvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
