# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_bzproductvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bzproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bzproductvariant',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
