# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20170214_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzproductvariant',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code'),
        ),
    ]
