# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20170214_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzproductvariant',
            name='bzproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.bzProduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bzproductvariant',
            name='pfcatalogvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfCatalogVariant', verbose_name='Printful Variant'),
        ),
    ]
