# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeseries',
            name='code',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Code'),
        ),
    ]
