# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_creativeseries_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeseries',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Code'),
        ),
    ]
