# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20161107_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code'),
        ),
    ]
