# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_creative_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creative',
            unique_together=set([('series', 'code')]),
        ),
    ]
