# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20161107_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='agreement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='artist',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='artist',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web Site'),
        ),
    ]
