# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20161107_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='has_agreement',
            field=models.BooleanField(default=False, verbose_name='Agreement in Place?'),
        ),
    ]
