# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0002_auto_20170211_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcatalogproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='pfprintfile',
            name='pfstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_printful.pfStore', verbose_name='Store'),
        ),
    ]
