# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0009_auto_20170212_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfcatalogsize',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Catalog Size', 'verbose_name_plural': 'Catalog Size'},
        ),
        migrations.AddField(
            model_name='pfcatalogsize',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='pfcatalogproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='pfcatalogproduct',
            name='variant_count',
            field=models.IntegerField(default=0, verbose_name='Variants'),
        ),
    ]
