# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0014_auto_20170212_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcatalogfilespec',
            name='colorsystem',
            field=models.CharField(choices=[('R', 'RGB'), ('Y', 'CMYK')], default='R', max_length=1, verbose_name='Color System'),
        ),
        migrations.AddField(
            model_name='pfcatalogfilespec',
            name='ratio',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Ratio'),
        ),
    ]
