# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0015_auto_20170212_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcatalogfilespec',
            name='name',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Name'),
        ),
    ]
