# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0017_auto_20170212_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcatalogcolor',
            name='label_clean',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Clean Label'),
        ),
    ]
