# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0018_pfcatalogcolor_label_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfcatalogcolor',
            name='code',
        ),
        migrations.AddField(
            model_name='pfcatalogcolor',
            name='hex_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Color Hex Code'),
        ),
    ]
