# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0019_auto_20170212_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcatalogcolor',
            name='code',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Code'),
        ),
    ]
