# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0020_pfcatalogcolor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcatalogsize',
            name='code',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='pfcatalogsize',
            name='label_clean',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Clean Label'),
        ),
    ]
