# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_printful', '0021_auto_20170212_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcatalogfilespec',
            name='height_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Height (in)'),
        ),
        migrations.AddField(
            model_name='pfcatalogfilespec',
            name='width_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Width (in)'),
        ),
    ]
