# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('image_height', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image_width', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='brand/', verbose_name='Brand Logo', width_field='image_width')),
                ('consumer_url', models.URLField(blank=True, default='', null=True, verbose_name='Consumer URL')),
                ('wholesale_url', models.URLField(blank=True, default='', null=True, verbose_name='Wholesale URL')),
                ('product_base_url', models.URLField(blank=True, default='', help_text="The URL that points to a specific product ID on the brand's website. Replace the ID with '{}'", null=True, verbose_name='Product URL Base')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'verbose_name': 'Brand',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Colors',
                'verbose_name': 'Color',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Google ID')),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('long_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Full Name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.GoogleCategory')),
            ],
            options={
                'verbose_name_plural': 'Google Categories',
                'verbose_name': 'Google Category',
                'ordering': ['long_name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('consumer_url', models.URLField(blank=True, null=True, verbose_name='Consumer URL')),
                ('dashboard_url', models.URLField(blank=True, null=True, verbose_name='Admin Dashboard URL')),
                ('apibase_url', models.URLField(blank=True, null=True, verbose_name='API Base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=64, verbose_name='API Key')),
                ('api_hash', models.CharField(blank=True, default='', max_length=96, verbose_name='API Hash')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
                'verbose_name': 'Manufacturer',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('age_group', models.CharField(choices=[('N', 'Newborn'), ('I', 'Infant'), ('T', 'Toddler'), ('K', 'Kids'), ('A', 'Adult')], default='A', max_length=1, verbose_name='Age Group')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Gender')),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Material')),
                ('pattern', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pattern')),
                ('size_type', models.CharField(blank=True, choices=[('N', 'None'), ('R', 'Regular'), ('T', 'Petite'), ('L', 'Plus'), ('B', 'Big and Tall'), ('M', 'Maternity')], default='R', max_length=1, verbose_name='Size Type')),
                ('size_system', models.CharField(choices=[('US', 'US - United States'), ('UK', 'UK - United Kingdom'), ('EU', 'EU - European Union'), ('DE', 'DE - Germany'), ('FR', 'FR - France'), ('JP', 'JP - Japan'), ('CN', 'CN - China'), ('IT', 'IT - Italy'), ('BR', 'BR - Brazil'), ('MEX', 'MEX - Mexico'), ('AU', 'AU - Australia')], default='US', max_length=3, verbose_name='Size System')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Product URL')),
                ('mobile_link', models.URLField(blank=True, default='', null=True, verbose_name='Mobile URL')),
                ('image_height', models.CharField(default='0', max_length=10, verbose_name='Image Height')),
                ('image_width', models.CharField(default='0', max_length=10, verbose_name='Image Width')),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product', verbose_name='Product Image', width_field='image_width')),
                ('additional_image_height', models.CharField(default='0', max_length=10, verbose_name='Additional Image Height')),
                ('additional_image_width', models.CharField(default='0', max_length=10, verbose_name='Additional Image Width')),
                ('additional_image', models.ImageField(blank=True, height_field='additional_image_height', null=True, upload_to='product_additional', verbose_name='Additional Image', width_field='additional_image_width')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('googlecategory', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.GoogleCategory', verbose_name='Google Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Sizes',
                'verbose_name': 'Size',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'verbose_name': 'Variant',
                'ordering': ['name', 'code'],
            },
        ),
    ]
