# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('image_height', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image_width', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='brand/', verbose_name='Brand Logo', width_field='image_width')),
                ('consumer_url', models.URLField(blank=True, default='', null=True, verbose_name='Consumer URL')),
                ('wholesale_url', models.URLField(blank=True, default='', null=True, verbose_name='Wholesale URL')),
                ('product_base_url', models.URLField(blank=True, default='', help_text="The URL that points to a specific product ID on the brand's website. Replace the ID with '{}'", null=True, verbose_name='Item URL Base')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('pms_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='PMS Code')),
                ('pms_family', models.CharField(blank=True, choices=[('U', 'Uncoated'), ('C', 'Coated'), ('M', 'Metallic'), ('N', 'Neon')], default='', max_length=1, null=True, verbose_name='PMS Family')),
                ('hex_code', models.CharField(blank=True, default='', help_text='The 6-digit hexidecimal code for this colour. Do not include the hash tag.', max_length=64, null=True, verbose_name='HEX Code')),
                ('r_value', models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Red Value')),
                ('g_value', models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Green Value')),
                ('b_value', models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Blue Value')),
            ],
            options={
                'verbose_name': 'Color',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='GoogleCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Google ID')),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('long_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Full Name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.GoogleCategory')),
            ],
            options={
                'verbose_name': 'Google Category',
                'ordering': ['long_name'],
                'verbose_name_plural': 'Google Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('age_group', models.CharField(choices=[('N', 'Newborn'), ('I', 'Infant'), ('T', 'Toddler'), ('K', 'Kids'), ('A', 'Adult')], default='A', max_length=1, verbose_name='Age Group')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Gender')),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Material')),
                ('pattern', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pattern')),
                ('size_type', models.CharField(blank=True, choices=[('N', 'None'), ('R', 'Regular'), ('T', 'Petite'), ('L', 'Plus'), ('B', 'Big and Tall'), ('M', 'Maternity')], default='R', max_length=1, verbose_name='Size Type')),
                ('size_system', models.CharField(choices=[('US', 'US - United States'), ('UK', 'UK - United Kingdom'), ('EU', 'EU - European Union'), ('DE', 'DE - Germany'), ('FR', 'FR - France'), ('JP', 'JP - Japan'), ('CN', 'CN - China'), ('IT', 'IT - Italy'), ('BR', 'BR - Brazil'), ('MEX', 'MEX - Mexico'), ('AU', 'AU - Australia')], default='US', max_length=3, verbose_name='Size System')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Item URL')),
                ('mobile_link', models.URLField(blank=True, default='', null=True, verbose_name='Mobile URL')),
                ('image_height', models.CharField(default='0', max_length=10, verbose_name='Image Height')),
                ('image_width', models.CharField(default='0', max_length=10, verbose_name='Image Width')),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product', verbose_name='Item Image', width_field='image_width')),
                ('additional_image_height', models.CharField(default='0', max_length=10, verbose_name='Additional Image Height')),
                ('additional_image_width', models.CharField(default='0', max_length=10, verbose_name='Additional Image Width')),
                ('additional_image', models.ImageField(blank=True, height_field='additional_image_height', null=True, upload_to='product_additional', verbose_name='Additional Image', width_field='additional_image_width')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('googlecategory', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.GoogleCategory', verbose_name='Google Category')),
            ],
            options={
                'verbose_name': 'Item',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('image_height', models.CharField(default='0', max_length=10, verbose_name='Image Height')),
                ('image_width', models.CharField(default='0', max_length=10, verbose_name='Image Width')),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product', verbose_name='Item Image', width_field='image_width')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Item URL')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Color')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
            ],
            options={
                'verbose_name': 'Item Variant',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Item Variants',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('consumer_url', models.URLField(blank=True, null=True, verbose_name='Consumer URL')),
                ('dashboard_url', models.URLField(blank=True, null=True, verbose_name='Admin Dashboard URL')),
                ('apibase_url', models.URLField(blank=True, null=True, verbose_name='API Base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=64, verbose_name='API Key')),
                ('api_hash', models.CharField(blank=True, default='', max_length=96, verbose_name='API Hash')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Vendor Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('brand', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Brand')),
                ('category', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Category')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('dt_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Added')),
                ('dt_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer Item',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Manufacturer Items',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name')),
                ('size', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Size')),
                ('color', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Color')),
                ('color_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Color Code')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('in_stock', models.BooleanField(default=False, verbose_name='In Stock?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('dt_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ManufacturerItem')),
            ],
            options={
                'verbose_name': 'Manufacturer Variant',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Manufacturer Variants',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('sortorder', models.IntegerField(blank=True, default=0, null=True)),
                ('grouping', models.CharField(blank=True, default='', max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Size',
                'ordering': ['sortorder', 'grouping'],
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Size'),
        ),
    ]
