# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
                ('is_variant_key', models.BooleanField(default=True, verbose_name='Variant?')),
            ],
            options={
                'verbose_name_plural': 'Attributes',
                'verbose_name': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'AttributeValues',
                'verbose_name': 'AttributeValue',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'verbose_name': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Creatives',
                'verbose_name': 'Creative',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
                'verbose_name': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('public_url', models.URLField(blank=True, null=True, verbose_name='Web')),
            ],
            options={
                'verbose_name_plural': 'Outlets',
                'verbose_name': 'Outlet',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
            ],
            options={
                'verbose_name_plural': 'Part',
                'verbose_name': 'Part',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
            ],
            options={
                'verbose_name_plural': 'Producers',
                'verbose_name': 'Producer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('code', models.CharField(blank=True, default='', max_length=2, verbose_name='ID Code')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
    ]
