# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturervariant',
            name='the_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
