# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_label_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Inside'), (2, 'Outside')], default=0, verbose_name='Product Label Type'),
        ),
    ]
