# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set([('code', 'brand')]),
        ),
    ]
