# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='b_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Blue Value'),
        ),
        migrations.AddField(
            model_name='color',
            name='g_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Green Value'),
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, default='', help_text='The 6-digit hexidecimal code for this colour. Do not include the hash tag.', max_length=64, null=True, verbose_name='HEX Code'),
        ),
        migrations.AddField(
            model_name='color',
            name='pms_code',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='PMS Code'),
        ),
        migrations.AddField(
            model_name='color',
            name='pms_family',
            field=models.CharField(blank=True, choices=[('U', 'Uncoated'), ('C', 'Coated'), ('M', 'Metallic'), ('N', 'Neon')], default='', max_length=1, null=True, verbose_name='PMS Family'),
        ),
        migrations.AddField(
            model_name='color',
            name='r_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-255', verbose_name='Red Value'),
        ),
    ]
