# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_manufacturervariant_the_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturervariant',
            old_name='the_price',
            new_name='base_price',
        ),
    ]
