# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161111_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['grouping', 'sortorder'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AddField(
            model_name='size',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='size',
            name='sortorder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
