# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161117_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
    ]
