# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161113_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturervariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Base Price'),
        ),
    ]
