# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161121_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
