# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161113_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureritem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
    ]
