# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161111_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('age_group', models.CharField(choices=[('N', 'Newborn'), ('I', 'Infant'), ('T', 'Toddler'), ('K', 'Kids'), ('A', 'Adult')], default='A', max_length=1, verbose_name='Age Group')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Gender')),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Material')),
                ('pattern', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pattern')),
                ('size_type', models.CharField(blank=True, choices=[('N', 'None'), ('R', 'Regular'), ('T', 'Petite'), ('L', 'Plus'), ('B', 'Big and Tall'), ('M', 'Maternity')], default='R', max_length=1, verbose_name='Size Type')),
                ('size_system', models.CharField(choices=[('US', 'US - United States'), ('UK', 'UK - United Kingdom'), ('EU', 'EU - European Union'), ('DE', 'DE - Germany'), ('FR', 'FR - France'), ('JP', 'JP - Japan'), ('CN', 'CN - China'), ('IT', 'IT - Italy'), ('BR', 'BR - Brazil'), ('MEX', 'MEX - Mexico'), ('AU', 'AU - Australia')], default='US', max_length=3, verbose_name='Size System')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Item URL')),
                ('mobile_link', models.URLField(blank=True, default='', null=True, verbose_name='Mobile URL')),
                ('image_height', models.CharField(default='0', max_length=10, verbose_name='Image Height')),
                ('image_width', models.CharField(default='0', max_length=10, verbose_name='Image Width')),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product', verbose_name='Item Image', width_field='image_width')),
                ('additional_image_height', models.CharField(default='0', max_length=10, verbose_name='Additional Image Height')),
                ('additional_image_width', models.CharField(default='0', max_length=10, verbose_name='Additional Image Width')),
                ('additional_image', models.ImageField(blank=True, height_field='additional_image_height', null=True, upload_to='product_additional', verbose_name='Additional Image', width_field='additional_image_width')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'verbose_name': 'Item',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='googlecategory',
        ),
        migrations.AlterField(
            model_name='brand',
            name='product_base_url',
            field=models.URLField(blank=True, default='', help_text="The URL that points to a specific product ID on the brand's website. Replace the ID with '{}'", null=True, verbose_name='Item URL Base'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product', verbose_name='Item Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Item URL'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='googlecategory',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.GoogleCategory', verbose_name='Google Category'),
        ),
    ]
