# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161111_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='ItemVariant',
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Item Variant', 'verbose_name_plural': 'Item Variants'},
        ),
    ]
