# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_manufactureritem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['code'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['brand__code', 'code', 'name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='color',
            name='pms_family',
            field=models.CharField(blank=True, choices=[('U', 'Uncoated'), ('C', 'Coated'), ('M', 'Metallic'), ('N', 'Neon'), ('X', 'TPX')], default='', max_length=1, null=True, verbose_name='PMS Family'),
        ),
    ]
