# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161219_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturervariant',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer'),
        ),
    ]
