# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20161114_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturervariant',
            name='code',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Code'),
        ),
    ]
