# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20161201_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='manufacturervariant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight (oz)'),
        ),
    ]
