# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 01:16
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20161111_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name',)),
        ),
    ]
