# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20161201_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='sortorder',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_ca',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping to Canada. Cost for the first item.', max_digits=6, verbose_name='Shipping (CA)'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_ca_addl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost for subsequent items after the first.', max_digits=6, verbose_name='Shipping (CA) Addl'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_us',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Domestic Shipping. Cost for the first item.', max_digits=6, verbose_name='Shipping (US)'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_us_addl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost for subsequent items after the first.', max_digits=6, verbose_name='Shipping (US) Addl'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_ww',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Global Shipping (ex US/CA). Cost for the first item.', max_digits=6, verbose_name='Shipping (WW)'),
        ),
        migrations.AlterField(
            model_name='manufacturervariant',
            name='shipping_ww_addl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost for subsequent items after the first.', max_digits=6, verbose_name='Shipping (WW) Addl'),
        ),
    ]
