# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161204_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set([('name', 'code', 'brand')]),
        ),
    ]
