# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161111_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Vendor Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('brand', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Brand')),
                ('category', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Category')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['name', 'code'],
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='VendorVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name')),
                ('size', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Size')),
                ('color', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Size')),
                ('color_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Size')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.VendorItem')),
            ],
            options={
                'verbose_name_plural': 'Item Variants',
                'ordering': ['name', 'code'],
                'verbose_name': 'Item Variant',
            },
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['sortorder', 'grouping'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
