# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161113_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='VendorItem',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Manufacturer Item', 'verbose_name_plural': 'Manufacturer Items'},
        ),
        migrations.AlterModelOptions(
            name='VendorVariant',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Manufacturer Variant', 'verbose_name_plural': 'Manufacturer Variants'},
        ),
        migrations.AddField(
            model_name='VendorItem',
            name='dt_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='VendorItem',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='VendorItem',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='VendorItem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer'),
        ),
        migrations.AddField(
            model_name='VendorVariant',
            name='dt_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='VendorVariant',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='VendorVariant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
    ]
