# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161204_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='sortorder',
            field=models.CharField(default='', max_length=12, verbose_name='Sort Order'),
        ),
    ]
