# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20161113_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='VendorVariant',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='In Stock?'),
        ),
        migrations.AlterField(
            model_name='VendorItem',
            name='dt_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='VendorItem',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
