# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20161204_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='h_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-100', verbose_name='Hue Value'),
        ),
        migrations.AddField(
            model_name='color',
            name='l_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-100', verbose_name='Luminance Value'),
        ),
        migrations.AddField(
            model_name='color',
            name='s_value',
            field=models.IntegerField(default=0, help_text='Scale of 0-100', verbose_name='Saturation Value'),
        ),
    ]
