# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20161113_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name')),
                ('size', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Size')),
                ('color', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Color')),
                ('color_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Color Code')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('in_stock', models.BooleanField(default=False, verbose_name='In Stock?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('dt_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer Variant',
                'verbose_name_plural': 'Manufacturer Variants',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.RenameModel(
            old_name='VendorItem',
            new_name='ManufacturerItem',
        ),
        migrations.RemoveField(
            model_name='vendorvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='VendorVariant',
        ),
        migrations.AddField(
            model_name='manufacturervariant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ManufacturerItem'),
        ),
    ]
