# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_manufacturervariant_color_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerItemDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Manufacturer Item Dimension',
                'ordering': ['name', 'code'],
                'verbose_name': 'Manufacturer Item Dimension',
            },
        ),
    ]
