# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_manufactureritemdimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerItemFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Additional Cost')),
                ('manufacturer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ManufacturerItem')),
            ],
            options={
                'verbose_name': 'Manufacturer Item File',
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Manufacturer Item Files',
            },
        ),
    ]
