# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20161206_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerFileLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('hashvalue', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Hash')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='URL')),
                ('filename', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Filename')),
                ('mime_type', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='MIME Type')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('dpi', models.IntegerField(default=0, verbose_name='DPI')),
                ('status', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Status')),
                ('created', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Created Stamp')),
                ('thumbnail_url', models.URLField(blank=True, default='', null=True, verbose_name='Thumbnail URL')),
                ('preview_url', models.URLField(blank=True, default='', null=True, verbose_name='Preview URL')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible?')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer')),
            ],
            options={
                'verbose_name': 'File Library Item',
                'verbose_name_plural': 'File Library Item',
                'ordering': ['name', 'code'],
            },
        ),
    ]
