# from .models import *
#
# def update(var1, var2, var3):
#     obj = ProductVariant.objects.get(product__sku=var1, color__name=var2)
#     obj.local_sku = var3
#     obj.save
#     print("--> {}".format(obj.local_sku))
#
# def run_it():
#     update('IP5-CS','Glossy','IP5-CS-GL')
#     update('IP5-CS','Matte','IP5-CS-MT')
#     update('IP6-BP1-CS-G','Glossy','IP6-BP1-CS-G-GL')
#     update('IP6-BP1-CS-G','Matte','IP6-BP1-CS-G-MT')
#     update('IP6-BP2B-CS-G','Glossy','IP6-BP2B-CS-G-GL')
#     update('IP6-BP3C-CS-G','Glossy','IP6-BP3C-CS-G-GL')
#     update('IP6-BP3C-CS-G','Matte','IP6-BP3C-CS-G-MT')
#     update('IP6-CS','Glossy','IP6-CS-GL')
#     update('IP6-CS','Matte','IP6-CS-MT')
#     update('IP6-CS-C-G','Glossy','IP6-CS-C-G-GL')
#     update('IP6-CS-C-G','Matte','IP6-CS-C-G-MT')
#     update('IP6-FW-D2P','Matte','IP6-FW-D2P-MT')
#     update('IP6-TC-CS','Glossy','IP6-TC-CS-GL')
#     update('IP6-TC-CS','Matte','IP6-TC-CS-MT')
#     update('IP6P-BP2B-CS-G','Glossy','IP6P-BP2B-CS-G-GL')
#     update('IP6P-CS','Glossy','IP6P-CS-GL')
#     update('IP6P-CS','Matte','IP6P-CS-MT')
#     update('IP6P-CS-C','Glossy','IP6P-CS-C-GL')
#     update('IP6P-CS-C','Matte','IP6P-CS-C-MT')
#     update('IP6P-FW-D2P','Matte','IP6P-FW-D2P-MT')
#     update('IP6P-TC-CS','Glossy','IP6P-TC-CS-GL')
#     update('IP6P-TC-CS','Matte','IP6P-TC-CS-MT')
#     update('IP6S-CS','Glossy','IP6S-CS-GL')
#     update('IP6S-CS','Matte','IP6S-CS-MT')
#     update('IP6S-TCB-CS','Glossy','IP6S-TCB-CS-GL')
#     update('IP6S-TCB-CS','Matte','IP6S-TCB-CS-MT')
#     update('IP6SP-CS-G','Glossy','IP6SP-CS-G-GL')
#     update('IP6SP-CS-G','Matte','IP6SP-CS-G-MT')
#     update('IP6SP-TCB-CS-G','Glossy','IP6SP-TCB-CS-G-GL')
#     update('IP6SP-TCB-CS-G','Matte','IP6SP-TCB-CS-G-MT')
#     update('IP7-BP2B-CS','Glossy','IP7-BP2B-CS-GL')
#     update('IP7-CS','Glossy','IP7-CS-GL')
#     update('IP7-CS','Matte','IP7-CS-MT')
#     update('IP7-FW-D2P','Matte','IP7-FW-D2P-MT')
#     update('IP7-TCB-CS','Glossy','IP7-TCB-CS-GL')
#     update('IP7-TCB-CS','Matte','IP7-TCB-CS-MT')
#     update('IP7P-BP2B-CS','Glossy','IP7P-BP2B-CS-GL')
#     update('IP7P-CS','Glossy','IP7P-CS-GL')
#     update('IP7P-CS','Matte','IP7P-CS-MT')
#     update('IP7P-FW-D2P','Matte','IP7P-FW-D2P-MT')
#     update('IP7P-TCB-CS','Glossy','IP7P-TCB-CS-GL')
#     update('IP7P-TCB-CS','Matte','IP7P-TCB-CS-MT')
#     update('LGG4-CS-G','Glossy','LGG4-CS-G-GL')
#     update('LGG4-TCB-CS-G','Glossy','LGG4-TCB-CS-G-GL')
#     update('SGN5-CS','Glossy','SGN5-CS-GL')
#     update('SGN5-TCB-CS-G','Glossy','SGN5-TCB-CS-G-GL')
#     update('SGS5-CS','Glossy','SGS5-CS-GL')
#     update('SGS5-CS','Matte','SGS5-CS-MT')
#     update('SGS5-TC-CS','Glossy','SGS5-TC-CS-GL')
#     update('SGS6-CS','Glossy','SGS6-CS-GL')
#     update('SGS6-CS','Matte','SGS6-CS-MT')
#     update('SGS6-FW-D2P','Glossy','SGS6-FW-D2P-GL')
#     update('SGS6-FW-D2P','Matte','SGS6-FW-D2P-MT')
#     update('SGS6-TCB-CS-G','Glossy','SGS6-TCB-CS-G-GL')
#     update('SGS6-TCB-CS-G','Matte','SGS6-TCB-CS-G-MT')
#     update('SGS6E-CS-G','Glossy','SGS6E-CS-G-GL')
#     update('SGS6E-CS-G','Matte','SGS6E-CS-G-MT')
#     update('SGS6E-FW-D2P','Glossy','SGS6E-FW-D2P-GL')
#     update('SGS6E-FW-D2P','Matte','SGS6E-FW-D2P-MT')
#     update('SGS6E-TCB-CS-G','Glossy','SGS6E-TCB-CS-G-GL')
#     update('SGS6E-TCB-CS-G','Matte','SGS6E-TCB-CS-G-MT')
#     update('SGS6EP-CS-G','Glossy','SGS6EP-CS-G-GL')
#     update('SGS6EP-CS-G','Matte','SGS6EP-CS-G-MT')
#     update('SGS6EP-TCB-CS-G','Glossy','SGS6EP-TCB-CS-G-GL')
#     update('SGS6EP-TCB-CS-G','Matte','SGS6EP-TCB-CS-G-MT')
#     update('SGS7-CS','Glossy','SGS7-CS-GL')
#     update('SGS7-CS','Matte','SGS7-CS-MT')
#     update('SGS7-FW-D2P','Glossy','SGS7-FW-D2P-GL')
#     update('SGS7-TCB-CS-G','Glossy','SGS7-TCB-CS-G-GL')
#     update('SGS7-TCB-CS-G','Matte','SGS7-TCB-CS-G-MT')
#     update('SGS7E-CS-G','Glossy','SGS7E-CS-G-GL')
#     update('SGS7E-CS-G','Matte','SGS7E-CS-G-MT')
#     update('SGS7E-TCB-CS','Glossy','SGS7E-TCB-CS-GL')
#     update('SGS7E-TCB-CS','Matte','SGS7E-TCB-CS-MT')
