# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooproductattribute',
            name='order_by',
            field=models.CharField(blank=True, choices=[('name', 'Sort by Name'), ('name_num', 'Sort by Name (Number)'), ('id', 'Sort by ID'), ('menu_order', 'Sort by Custom Menu Order')], default='', max_length=255, null=True, verbose_name='Order By'),
        ),
        migrations.AlterField(
            model_name='wooproductattribute',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Basic Text'), ('color picker', 'Color Picker'), ('image select', 'Image Select'), ('text label', 'Text Label')], default='', max_length=255, null=True, verbose_name='Type'),
        ),
    ]
