# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woovariant',
            options={'ordering': ['wid'], 'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.RemoveField(
            model_name='woovariant',
            name='count',
        ),
        migrations.RemoveField(
            model_name='woovariant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='woovariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='woovariant',
            name='slug',
        ),
        migrations.AddField(
            model_name='woovariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='variant_attributes', to='outlet_woocommerce.wooAttribute', verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='backordered',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if a product is on backorder (if the product have the stock_quantity negative).', verbose_name='Backordered?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='backorders',
            field=models.CharField(choices=[('no', 'Do Not Allow'), ('notify', 'Allow, But Notify Customer'), ('yes', 'Allow')], default='no', help_text='If managing stock, this controls if backorders are allowed. If enabled, stock quantity can go below 0. Default is no. Options are: no (Do not allow), notify (Allow, but notify customer), and yes (Allow).', max_length=255, verbose_name='Backorders'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='backorders_allowed',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if backorders are allowed.', verbose_name='Backorders Allowed?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_created',
            field=models.DateField(blank=True, help_text='READONLY. The date the product was created, in the site’s timezone.', null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_modified',
            field=models.DateField(blank=True, help_text='READONLY. The date the product was last modified, in the site’s timezone.', null=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_on_sale_from',
            field=models.DateField(blank=True, help_text='Start date of sale price. Date in the YYYY-MM-DD format.', null=True, verbose_name='On Sale From'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_on_sale_to',
            field=models.DateField(blank=True, help_text='End date of sale price. Date in the YYYY-MM-DD format.', null=True, verbose_name='On Sale To'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='dimension_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='download_expiry',
            field=models.IntegerField(default=-1, help_text='Number of days that the customer has up to be able to download the product, the -1 means that downloads never expires. Default is -1.', verbose_name='Download Expiry'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='download_limit',
            field=models.IntegerField(default=-1, help_text='Amount of times the product can be downloaded, the -1 values means unlimited re-downloads. Default is -1.', verbose_name='Download Limit'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='downloadable',
            field=models.BooleanField(default=False, help_text='If the product is downloadable. Downloadable products give access to a file upon purchase. Default is false.', verbose_name='Downloadable?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='images',
            field=models.ManyToManyField(blank=True, to='outlet_woocommerce.wooImage', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Controls whether or not the product is listed as “in stock” or “out of stock” on the frontend. Default is true.', verbose_name='In Stock?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='Stock management at product level. Default is false.', verbose_name='Manage Stock'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='on_sale',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if the product is on sale.', verbose_name='On Sale?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='permalink',
            field=models.URLField(blank=True, verbose_name='Permalink'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='price',
            field=models.CharField(blank=True, default='', help_text='READONLY. Current product price. This is set from regular_price and sale_price.', max_length=255, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='price_html',
            field=models.CharField(blank=True, default='', help_text='READONLY. Price formatted in HTML.', max_length=1000, null=True, verbose_name='Price HTML'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='purchasable',
            field=models.BooleanField(default=True, help_text='READONLY. Shows if the product can be bought.', verbose_name='Purchasable?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='regular_price',
            field=models.CharField(blank=True, default='', help_text='Product regular price.', max_length=255, null=True, verbose_name='Regular Price'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='sale_price',
            field=models.CharField(blank=True, default='', help_text='Product sale price.', max_length=255, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooShippingClass'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Unique identifier.', max_length=255, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Stock quantity. If is a variable product this value will be used to control stock for all variations, unless you define stock at variation level.', verbose_name='Stock Quantity'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='tax_class',
            field=models.CharField(blank=True, default='', help_text='The tax class.', max_length=255, null=True, verbose_name='Tax Class'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('shipping', 'Shipping Only'), ('none', 'None')], default='taxable', help_text='Tax status. Default is taxable. Options: taxable, shipping (Shipping only) and none.', max_length=15, verbose_name='Tax Status'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='virtual',
            field=models.BooleanField(default=False, help_text='If the product is virtual. Virtual products are intangible and aren’t shipped. Default is false.', verbose_name='Virtual?'),
        ),
        migrations.AddField(
            model_name='woovariant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product weight in decimal format.', max_digits=10, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='wooproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_attributes', to='outlet_woocommerce.wooAttribute', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='woovariant',
            name='wid',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID'),
        ),
    ]
