# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0002_auto_20170212_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='wooProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooStore')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'ordering': ['store', 'name'],
                'verbose_name_plural': 'Product Tags',
            },
        ),
    ]
