# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0002_auto_20170218_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wooimage',
            options={'ordering': ['name', 'wid'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='wooimage',
            name='code',
        ),
        migrations.AddField(
            model_name='wooimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wooimage',
            name='date_created',
            field=models.DateField(blank=True, help_text='READONLY. The date the product was created, in the site’s timezone.', null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='date_modified',
            field=models.DateField(blank=True, help_text='READONLY. The date the product was last modified, in the site’s timezone.', null=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='position',
            field=models.IntegerField(default=0, help_text='Image position. 0 means that the image is featured.', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='src',
            field=models.URLField(blank=True, help_text='Image URL. In write-mode used to upload new images.', null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='wooimage',
            name='wid',
            field=models.CharField(blank=True, default='', help_text='Image ID (attachment ID). In write-mode used to attach pre-existing images.', max_length=16, null=True, verbose_name='Woo ID'),
        ),
    ]
