# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0003_auto_20170219_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wooimage',
            options={'ordering': ['name', 'wid'], 'verbose_name': 'Image Association', 'verbose_name_plural': 'Image Associations'},
        ),
    ]
