# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0003_wooproducttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='wooProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('wid', models.IntegerField(blank=True, default=0, null=True, verbose_name='Woo ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('parent', models.IntegerField(default=0, verbose_name='Parent ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('display', models.CharField(choices=[('default', 'Default'), ('products', 'Products'), ('subcategories', 'Subcategories'), ('both', 'Display Both')], default='default', max_length=255, verbose_name='Display')),
                ('menu_order', models.IntegerField(default=0, verbose_name='Menu Order')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('image_id', models.IntegerField(default=0, verbose_name='Image ID')),
                ('image_date_created', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Created')),
                ('image_date_updated', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Updated')),
                ('image_src', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image SRC')),
                ('image_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Name')),
                ('image_alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooStore')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categorys',
                'ordering': ['store', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='wooproducttag',
            name='wid',
            field=models.IntegerField(default=0, verbose_name='Woo ID'),
        ),
    ]
