# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0004_auto_20170213_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wooproductcategory',
            options={'ordering': ['store', 'name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='wooproductcategory',
            name='image_date_updated',
        ),
        migrations.AddField(
            model_name='wooproductcategory',
            name='image_date_modified',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Image Modified'),
        ),
    ]
