# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0005_auto_20170213_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='wpMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('date_gmt', models.DateTimeField(blank=True, null=True, verbose_name='Date GMT')),
                ('guid', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='GUID')),
                ('wid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', null=True, verbose_name='Link')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified')),
                ('modified_gmt', models.DateTimeField(blank=True, null=True, verbose_name='Modified GMT')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('type', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Type')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('author', models.IntegerField(default=0, verbose_name='Author')),
                ('comment_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=255, verbose_name='Comment Status')),
                ('ping_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=255, verbose_name='Ping Status')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alternate Text')),
                ('caption', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Caption')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('media_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Media Type')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MIME Type')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Width')),
                ('post', models.IntegerField(default=0, verbose_name='Post ID')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('template', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['title', 'guid'],
                'verbose_name': 'Media',
            },
        ),
    ]
