# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0006_wpmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='wpMediaSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('file', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='File')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MIME Type')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('source_url', models.URLField(blank=True, default='', null=True, verbose_name='Source URL')),
            ],
            options={
                'ordering': ['name', 'file'],
                'verbose_name': 'wpMedia Size',
                'verbose_name_plural': 'wpMedia Sizes',
            },
        ),
        migrations.AddField(
            model_name='wpmedia',
            name='file',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='wpmedia',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='wpmediasize',
            name='wpmedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wpMedia', verbose_name='Media'),
        ),
    ]
