# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0007_auto_20170213_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpmediasize',
            options={'ordering': ['name', 'file'], 'verbose_name': 'Media Size', 'verbose_name_plural': 'Media Sizes'},
        ),
        migrations.AddField(
            model_name='wpmedia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='wpmedia',
            name='woostore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooStore'),
        ),
    ]
