# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0011_wooproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wooproduct',
            options={'ordering': ['name', 'wid'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
