# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0012_auto_20170213_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='woostore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woocommerce.wooStore', verbose_name='Store'),
        ),
    ]
