# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woocommerce', '0013_wooproduct_woostore'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
