# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InfoContent',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, default='', max_length=5000, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LayerType',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('id', models.IntegerField(default=0)),
                ('uid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='Coming Soon?')),
                ('has_available_product_variants', models.BooleanField(default=False, verbose_name='Variant?')),
                ('has_product_templates', models.BooleanField(default=False, verbose_name='Has Template?')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Desc')),
                ('max_zoom', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priceinfo_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('priceinfo_currencycode', models.CharField(default='USD', max_length=3, null=True)),
                ('priceinfo_currencydigits', models.IntegerField(default=2)),
                ('priceinfo_currencyformat', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('priceinfo_formattedprice', models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Price')),
                ('retailprice_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('retailprice_currencycode', models.CharField(default='USD', max_length=3, null=True)),
                ('retailprice_currencydigits', models.IntegerField(default=2)),
                ('retailprice_currencyformat', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('retailprice_formattedprice', models.CharField(blank=True, default='', max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('index', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('image_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.ImageType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pkid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('info_key', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('index', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.ContentType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SpaceLayer',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pkid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('include_in_print', models.BooleanField(default=False)),
                ('x1', models.IntegerField(default=0)),
                ('x2', models.IntegerField(default=0)),
                ('y1', models.IntegerField(default=0)),
                ('y2', models.IntegerField(default=0)),
                ('zIndex', models.IntegerField(default=0)),
                ('layer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.LayerType')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TemplateSpace',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='sku')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_templates', models.BooleanField(default=False)),
                ('max_images', models.IntegerField(default=0)),
                ('priceinfo_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('priceinfo_currencycode', models.CharField(default='USD', max_length=3, null=True)),
                ('priceinfo_currencydigits', models.IntegerField(default=2)),
                ('priceinfo_currencyformat', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('priceinfo_formattedprice', models.CharField(blank=True, default='', max_length=24, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('option_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sort_value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Variant')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VariantTemplate',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Variant')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='templatespace',
            name='VariantTemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.VariantTemplate'),
        ),
        migrations.AddField(
            model_name='spacelayer',
            name='templatespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.TemplateSpace'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api_gooten.ProductCategory'),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='productinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gooten.ProductInfo'),
        ),
    ]
