# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0002_productimage_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='productimage',
            name='imagetypes',
            field=models.ManyToManyField(blank=True, to='api_gooten.ImageType'),
        ),
    ]
