# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0003_auto_20161229_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='api_gooten/productimage', verbose_name='Item Image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_height',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_width',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pkid'),
        ),
    ]
