# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0004_auto_20161229_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantoption',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='api_gooten/variant_option', verbose_name='Item Image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='image_height',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='image_width',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Width'),
        ),
        migrations.AddField(
            model_name='varianttemplate',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='api_gooten/variant_template', verbose_name='Item Image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='varianttemplate',
            name='image_height',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='varianttemplate',
            name='image_width',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Width'),
        ),
    ]
