# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0005_auto_20161229_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantoption',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', max_length=1000, null=True, upload_to='api_gooten/variant_option', verbose_name='Item Image', width_field='image_width'),
        ),
    ]
