# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0006_auto_20161229_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pkid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('option_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pkid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sort_value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_height', models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Height')),
                ('image_width', models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Image Width')),
                ('image', models.ImageField(blank=True, height_field='image_height', max_length=1000, null=True, upload_to='api_gooten/attribute', verbose_name='Item Image', width_field='image_width')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Attribute')),
            ],
            options={
                'ordering': ('sort_value',),
            },
        ),
        migrations.AlterModelOptions(
            name='variantoption',
            options={'ordering': ('value__sort_order',)},
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='sort_value',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='value_id',
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_gooten.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_gooten.Variant'),
        ),
    ]
