# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_manufacturervariant_manufacturer'),
        ('api_gooten', '0007_auto_20161229_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',), 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('sort_value',), 'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'ordering': ('name',), 'verbose_name': 'Content Type', 'verbose_name_plural': 'Content Types'},
        ),
        migrations.AlterModelOptions(
            name='imagetype',
            options={'ordering': ('name',), 'verbose_name': 'Image Type', 'verbose_name_plural': 'Image Types'},
        ),
        migrations.AlterModelOptions(
            name='infocontent',
            options={'ordering': ('-created',), 'verbose_name': 'Info Content', 'verbose_name_plural': 'Info Content'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('id',), 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-created',), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ('-created',), 'verbose_name': 'Product Info', 'verbose_name_plural': 'Product Info'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('product', 'sku'), 'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterModelOptions(
            name='variantoption',
            options={'ordering': ('value__sort_value', 'value__attribute'), 'verbose_name': 'Variant Option', 'verbose_name_plural': 'Variant Options'},
        ),
        migrations.AddField(
            model_name='variant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_brand', to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_color', to='catalog.Color'),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_size', to='catalog.Size'),
        ),
    ]
