# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0009_auto_20161231_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='c_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_brand', to='catalog.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='c_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_color', to='catalog.Color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='c_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item', to='catalog.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='c_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_size', to='catalog.Size', verbose_name='Size'),
        ),
    ]
