# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gooten', '0010_auto_20170102_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianttemplate',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='templatespace',
            old_name='VariantTemplate',
            new_name='variant_template',
        ),
        migrations.AddField(
            model_name='imagetype',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spacelayer',
            name='id',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='varianttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
