# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web Site')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('agreement', models.TextField(blank=True, default='', null=True, verbose_name='Agreement Notes')),
                ('has_agreement', models.BooleanField(default=False, verbose_name='Agreement in Place?')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('description', models.TextField(blank=True, help_text='This will appear in the customer-facing product listing.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Artists',
                'verbose_name': 'Artist',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('status', models.CharField(blank=True, choices=[('N', 'New'), ('V', 'In Development'), ('L', 'Live'), ('D', 'Deferred')], default='N', max_length=1, null=True, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('description', models.TextField(blank=True, help_text='This will appear in the customer-facing product listing.', null=True, verbose_name='Description')),
                ('reference_url', models.URLField(blank=True, null=True, verbose_name='Reference URL')),
                ('reference_note', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Reference Note')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.Artist')),
            ],
            options={
                'ordering': ['series__code', 'code', 'name'],
                'verbose_name_plural': 'Designs',
                'verbose_name': 'Design',
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('web_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('category', models.CharField(blank=True, choices=[('X', 'Unknown'), ('W', 'Web Shop'), ('M', 'Marketplace'), ('R', 'Retail'), ('L', 'License')], default='X', max_length=1, verbose_name='Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('logo_hires_height', models.IntegerField(default=0)),
                ('logo_hires_width', models.IntegerField(default=0)),
                ('logo_hires', models.ImageField(blank=True, height_field='logo_hires_height', null=True, upload_to='', verbose_name='Press-Ready Logo', width_field='logo_hires_width')),
            ],
            options={
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Sales Channels',
                'verbose_name': 'Sales Channel',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('description', models.TextField(blank=True, help_text='This will appear in the customer-facing product listing.', null=True, verbose_name='Description')),
                ('creative_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.Artist', verbose_name='Creative Lead')),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.SalesChannel', verbose_name='Sales Channel')),
            ],
            options={
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Series',
                'verbose_name': 'Series',
            },
        ),
        migrations.AddField(
            model_name='design',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='design',
            unique_together=set([('series', 'code')]),
        ),
    ]
