# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creative',
            new_name='Design',
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['series__code', 'code', 'name'], 'verbose_name': 'Design', 'verbose_name_plural': 'Designs'},
        ),
    ]
