# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0002_creative_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
