# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0003_series_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ['series__code', 'code', 'name'], 'verbose_name': 'Creative', 'verbose_name_plural': 'Creative'},
        ),
    ]
