# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Slug')),
                ('app_added', models.DateTimeField(auto_now_add=True)),
                ('app_last_sync', models.DateTimeField(auto_now=True)),
                ('permalink', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Permalink')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified')),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External'), ('variable', 'Variable')], default='simple', max_length=15, verbose_name='Type')),
                ('status', models.CharField(choices=[(('draft',), 'Draft'), ('pending', 'Pending'), ('private', 'Private'), ('publish', 'Publish')], default='publish', max_length=15, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('catalog_visibility', models.CharField(choices=[('visible', 'Visible'), ('catalog', 'Catalog Only'), ('search', 'Search Only'), ('hidden', 'Hidden')], default='visible', max_length=10, verbose_name='Visibility')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('sku', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SKU')),
                ('price', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Price')),
                ('regular_price', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Regular Price')),
                ('sale_price', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sale Price')),
                ('date_on_sale_from', models.DateField(blank=True, null=True, verbose_name='On Sale From')),
                ('date_on_sale_to', models.DateField(blank=True, null=True, verbose_name='On Sale To')),
                ('price_html', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Price HTML')),
                ('on_sale', models.BooleanField(default=False, verbose_name='On Sale?')),
                ('purchasable', models.BooleanField(default=True, verbose_name='Purchasable?')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total Sales')),
                ('virtual', models.BooleanField(default=False, verbose_name='Virtual?')),
                ('downloadable', models.BooleanField(default=False, verbose_name='Downloadable?')),
                ('download_limit', models.IntegerField(default=-1, verbose_name='Download Limit')),
                ('download_expiry', models.IntegerField(default=-1, verbose_name='Download Expiry')),
                ('download_type', models.CharField(choices=[('standard', 'Standard Product'), ('application', 'Application/Software'), ('music', 'Music')], default='standard', max_length=15, verbose_name='Download Type')),
                ('external_url', models.URLField(blank=True, default='', null=True, verbose_name='External URL')),
                ('button_text', models.CharField(blank=True, default='', help_text='Product external button text. Only for external products.', max_length=255, null=True, verbose_name='Button Text')),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('shipping', 'Shipping Only'), ('none', 'None')], default='taxable', max_length=15, verbose_name='Tax Status')),
                ('tax_class', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tax Class')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='Manage Stock')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock?')),
                ('backorders', models.CharField(choices=[('no', 'Do Not Allow'), ('notify', 'Allow, But Notify Customer'), ('yes', 'Allow')], default='no', max_length=255, verbose_name='Backorders')),
                ('backorders_allowed', models.BooleanField(default=False, verbose_name='Backorders Allowed?')),
                ('backordered', models.BooleanField(default=False, verbose_name='Backordered?')),
                ('sold_individually', models.BooleanField(default=False, verbose_name='Sold Individually?')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Product weight in decimal format.', max_digits=10, verbose_name='Weight')),
                ('shipping_required', models.BooleanField(default=False, verbose_name='Requires Shipping?')),
                ('shipping_taxable', models.BooleanField(default=False, verbose_name='Taxable Shipping?')),
                ('reviews_allowed', models.BooleanField(default=True, verbose_name='Reviewed Allowed?')),
                ('average_rating', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Rating Count')),
                ('purchase_note', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Purchase Note')),
                ('menu_order', models.IntegerField(default=0, verbose_name='Menu Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('web_url', models.URLField(blank=True, default='', null=True, verbose_name='Website')),
                ('consumer_key', models.CharField(blank=True, max_length=43, null=True, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(blank=True, max_length=43, null=True, verbose_name='Consumer Secret')),
                ('num_products', models.IntegerField(default=0, verbose_name='Product Count')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shop',
                'ordering': ['name', 'code'],
                'verbose_name': 'Shop',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
    ]
