# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
    ]
