# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0002_auto_20161116_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_html',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Price HTML'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sale Price'),
        ),
    ]
