# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0003_auto_20161116_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.CharField(blank=True, default='', help_text='READONLY. Reviews average rating.', max_length=15, null=True, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='backordered',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if a product is on backorder (if the product have the stock_quantity negative).', verbose_name='Backordered?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='backorders',
            field=models.CharField(choices=[('no', 'Do Not Allow'), ('notify', 'Allow, But Notify Customer'), ('yes', 'Allow')], default='no', help_text='If managing stock, this controls if backorders are allowed. If enabled, stock quantity can go below 0. Default is no. Options are: no (Do not allow), notify (Allow, but notify customer), and yes (Allow).', max_length=255, verbose_name='Backorders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='backorders_allowed',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if backorders are allowed.', verbose_name='Backorders Allowed?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('catalog', 'Catalog Only'), ('search', 'Search Only'), ('hidden', 'Hidden')], default='visible', help_text='Catalog visibility. Default is visible. Options: visible (Catalog and search), catalog (Only in catalog), search (Only in search) and hidden (Hidden from all).', max_length=10, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='', help_text='READONLY. Unique identifier for the resource.', max_length=16, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text="READONLY. The date the product was created. In the site's timezone.", null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text="READONLY. The date the product was last modified, in the site's timezone.", null=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_on_sale_from',
            field=models.DateField(blank=True, help_text='Start date of sale price. Date in the YYYY-MM-DD format.', null=True, verbose_name='On Sale From'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_on_sale_to',
            field=models.DateField(blank=True, help_text='End date of sale price. Date in the YYYY-MM-DD format.', null=True, verbose_name='On Sale To'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_expiry',
            field=models.IntegerField(default=-1, help_text='Number of days that the customer has up to be able to download the product, the -1 means that downloads never expires. Default is -1.', verbose_name='Download Expiry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_limit',
            field=models.IntegerField(default=-1, help_text='Amount of times the product can be downloaded, the -1 values means unlimited re-downloads. Default is -1.', verbose_name='Download Limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_type',
            field=models.CharField(choices=[('standard', 'Standard Product'), ('application', 'Application/Software'), ('music', 'Music')], default='standard', help_text="Download type, this controls the schema on the front-end. Default is standard. Options: 'standard' (Standard Product), application (Application/Software) and music (Music).", max_length=15, verbose_name='Download Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='downloadable',
            field=models.BooleanField(default=False, help_text='If the product is downloadable. Downloadable products give access to a file upon purchase. Default is false.', verbose_name='Downloadable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Product external URL. Only for external products.', null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured product. Default is false.', verbose_name='Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Controls whether or not the product is listed as “in stock” or “out of stock” on the frontend. Default is true.', verbose_name='In Stock?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Local flag to ensure depreciated products don't break the datastore.", verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='Stock management at product level. Default is false.', verbose_name='Manage Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='Menu order, used to custom sort products.', verbose_name='Menu Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Product name.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if the product is on sale.', verbose_name='On Sale?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Product parent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='permalink',
            field=models.CharField(blank=True, default='', help_text='READONLY. Product URL.', max_length=255, null=True, verbose_name='Permalink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', help_text='READONLY. Current product price. This is setted from regular_price and sale_price.f', max_length=255, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_html',
            field=models.CharField(blank=True, default='', help_text='READONLY. Price formatted in HTML.', max_length=1000, null=True, verbose_name='Price HTML'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External'), ('variable', 'Variable')], default='simple', help_text='Product type. Default is simple. In general, do not change this.', max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchasable',
            field=models.BooleanField(default=True, help_text='READONLY. Shows if the product can be bought.', verbose_name='Purchasable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_note',
            field=models.CharField(blank=True, default='', help_text='Optional note to send the customer after purchase.', max_length=255, null=True, verbose_name='Purchase Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='READONLY. Amount of reviews that the product have.', verbose_name='Rating Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.CharField(blank=True, default='', help_text='Product regular price.', max_length=255, null=True, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_allowed',
            field=models.BooleanField(default=True, help_text='Allow reviews. Default is true.', verbose_name='Reviewed Allowed?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, default='', help_text='Product sale price.', max_length=255, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_required',
            field=models.BooleanField(default=False, help_text='READONLY. Shows if the product need to be shipped.', verbose_name='Requires Shipping?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_taxable',
            field=models.BooleanField(default=False, help_text='READONLY. Shows whether or not the product shipping is taxable.', verbose_name='Taxable Shipping?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Product short description.', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Unique identifier.', max_length=255, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Product slug.', max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_individually',
            field=models.BooleanField(default=False, help_text='Allow one item to be bought in a single order. Default is false.', verbose_name='Sold Individually?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(('draft',), 'Draft'), ('pending', 'Pending'), ('private', 'Private'), ('publish', 'Publish')], default='publish', help_text='Product status (post status). Default is publish.', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Stock quantity. If is a variable product this value will be used to control stock for all variations, unless you define stock at variation level.', verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_class',
            field=models.CharField(blank=True, default='', help_text='The tax class.', max_length=255, null=True, verbose_name='Tax Class'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('shipping', 'Shipping Only'), ('none', 'None')], default='taxable', help_text='Tax status. Default is taxable. Options: taxable, shipping (Shipping only) and none.', max_length=15, verbose_name='Tax Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(default=0, help_text='READONLY. Amount of sales.', verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual',
            field=models.BooleanField(default=False, help_text='If the product is virtual. Virtual products are intangible and aren’t shipped. Default is false.', verbose_name='Virtual?'),
        ),
    ]
