# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161117_2358'),
        ('outlet_woo', '0003_auto_20161118_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_item', to='catalog.Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_design', to='creative.Design'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', help_text='READONLY. Current product price. This is set from regular_price and sale_price.', max_length=255, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
    ]
