# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0004_auto_20161116_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York'),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
    ]
