# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0005_auto_20161119_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='ProductDefaultAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Default Attributes',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Default Attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Dimensions',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Dimension',
            },
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Downloads',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Download',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Tags',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Tag',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
            ],
            options={
                'verbose_name_plural': 'Product Variations',
                'ordering': ['name', 'code'],
                'verbose_name': 'Product Variation',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_design', to='creative.Design'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_item', to='catalog.Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='productdownload',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='productdimension',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='productdefaultattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
    ]
