# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0005_auto_20161116_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', help_text='Image ID (attachment ID). In write-mode used to attach pre-existing images.', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('app_added', models.DateTimeField(auto_now_add=True, help_text='')),
                ('app_last_sync', models.DateTimeField(auto_now=True, help_text='')),
                ('date_created', models.DateTimeField(blank=True, help_text="READONLY. The date the product was created. In the site's timezone.", null=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(blank=True, help_text="READONLY. The date the product was last modified, in the site's timezone.", null=True, verbose_name='Modified')),
                ('src', models.URLField(help_text='In write-mode used to upload new images.', verbose_name='Image URL')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alternative Text')),
                ('position', models.IntegerField(default=1, help_text='0 means that the image is featured.', verbose_name='Image Position')),
            ],
            options={
                'verbose_name_plural': 'ProductImage',
                'ordering': ['name', 'code'],
                'verbose_name': 'ProductImage',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Product'),
        ),
    ]
