# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0006_auto_20161116_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='outlet_woo/productimage', verbose_name='Local Image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_height',
            field=models.CharField(default='0', max_length=10, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_width',
            field=models.CharField(default='0', max_length=10, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_added',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='app_last_sync',
            field=models.DateTimeField(auto_now=True, help_text=''),
        ),
    ]
