# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlet_woo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_lastgenerated', models.DateTimeField(blank=True, null=True, verbose_name='Last Generated')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop')),
            ],
            options={
                'ordering': ['name', 'code'],
                'verbose_name_plural': 'Data Feeds',
                'verbose_name': 'Data Feed',
            },
        ),
        migrations.CreateModel(
            name='DataFeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('link', models.URLField(blank=True)),
                ('image_link', models.URLField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=70, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('google_product_category', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('product_type', models.CharField(blank=True, default='', max_length=750, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('mpn', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('item_group_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('age_group', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_label', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shopfeeds.DataFeed')),
            ],
            options={
                'ordering': ['feed', 'identifier'],
                'verbose_name_plural': 'Data Feed Items',
                'verbose_name': 'Data Feed Item',
            },
        ),
    ]
