# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('cred_type', models.CharField(default='service_account', max_length=128, verbose_name='Type')),
                ('project_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Project ID')),
                ('private_key_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Private Key ID')),
                ('private_key', models.TextField(blank=True, default='', null=True, verbose_name='Private Key')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Client Email')),
                ('client_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Client ID')),
                ('auth_uri', models.URLField(blank=True, verbose_name='Auth URI')),
                ('token_uri', models.URLField(blank=True, verbose_name='Token URL')),
                ('auth_provider_x509_cert_url', models.URLField(blank=True, verbose_name='Authentication Provider Cert URL')),
                ('client_x509_cert_url', models.URLField(blank=True, verbose_name='Client x509 Certificate URL')),
            ],
            options={
                'verbose_name_plural': 'Google Credentials',
                'verbose_name': 'Google Credential',
                'ordering': ['name', 'code'],
            },
        ),
    ]
