# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet_woo', '0006_auto_20161215_1741'),
        ('app_shopfeeds', '0002_auto_20161215_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='outlet_woo.Shop'),
            preserve_default=False,
        ),
    ]
