# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopfeeds', '0006_auto_20161219_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeed',
            name='date_lastgenerated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Generated'),
        ),
    ]
