# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('value', models.TextField(blank=True, default='', max_length=255, verbose_name='Value')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Additional Setting',
                'verbose_name_plural': 'Additional Settings',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(verbose_name='Aura ID')),
                ('name', models.TextField(blank=True, default='', max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(verbose_name='Aura ID')),
                ('name', models.TextField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('code', models.TextField(blank=True, default='', max_length=6, verbose_name='Hex Code')),
                ('group', models.TextField(blank=True, default='', max_length=6, verbose_name='Group')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(verbose_name='Aura ID')),
                ('name', models.TextField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('option_name', models.TextField(blank=True, default='', max_length=255, verbose_name='Option Name')),
                ('company', models.TextField(blank=True, default='', max_length=255, verbose_name='Company')),
                ('zone', models.TextField(blank=True, default='', max_length=255, verbose_name='Zone')),
                ('group', models.TextField(blank=True, default='', max_length=100, verbose_name='Group')),
                ('first_item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additional_item_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(verbose_name='Aura ID')),
                ('name', models.TextField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('group', models.TextField(blank=True, default='', max_length=255, verbose_name='Product Group')),
                ('plus_size_charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
