# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsettings',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='additionalsettings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Hex Code'),
        ),
        migrations.AlterField(
            model_name='color',
            name='group',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='option_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='size',
            name='group',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Product Group'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
