# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0002_auto_20161023_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ('group_name', 'option_name'), 'verbose_name': 'Shipping', 'verbose_name_plural': 'Shipping'},
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='aura_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='group',
        ),
        migrations.AddField(
            model_name='shipping',
            name='group_id',
            field=models.IntegerField(default=0, null=True, verbose_name='Product Group'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='option_id',
            field=models.IntegerField(default=0, null=True, verbose_name='Aura ID'),
        ),
    ]
