# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0003_auto_20161023_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(verbose_name='Aura ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.Brand')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ('name',),
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(default=0, verbose_name='Aura ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aura_id', models.IntegerField(default=0, verbose_name='Aura ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Shipping Option',
                'verbose_name_plural': 'Shipping Options',
            },
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ('option', 'group'), 'verbose_name': 'Shipping', 'verbose_name_plural': 'Shipping'},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='option_name',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.Shipping'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ProductGroup'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ShippingOption'),
        ),
    ]
