# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0004_auto_20161023_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Shipping Zones',
                'verbose_name': 'Shipping Zone',
            },
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ShippingZone'),
        ),
    ]
