# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0005_auto_20161023_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='zone',
        ),
    ]
