# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0006_remove_shipping_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ShippingZone'),
        ),
    ]
