# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0007_shipping_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
        migrations.AddField(
            model_name='product',
            name='productgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ProductGroup'),
        ),
    ]
