# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0008_auto_20161023_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_image_url',
            field=models.URLField(blank=True, verbose_name='Size Chart URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.ProductGroup', verbose_name='Product Group'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.Country'),
        ),
    ]
