# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0012_auto_20161023_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_brightness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_hue',
            field=models.IntegerField(default=0),
        ),
    ]
