# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0013_auto_20161024_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('color_brightness', 'color_hue'), 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('-color', 'size__aura_id'), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_brightness',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hue',
        ),
        migrations.AddField(
            model_name='color',
            name='color_brightness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='color',
            name='color_hue',
            field=models.IntegerField(default=0),
        ),
    ]
