# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0014_auto_20161024_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('color_hue', 'color_brightness'), 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('name',), 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('-color__code', 'size__aura_id'), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(blank=True, default=0, null=True), null=True, upload_to='product/', verbose_name='Product Image', width_field=models.IntegerField(blank=True, default=0, null=True)),
        ),
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
