# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0015_auto_20161024_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=models.CharField(blank=True, default='', max_length=100, null=True), null=True, upload_to='product/', verbose_name='Product Image', width_field=models.CharField(blank=True, default='', max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_height',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_width',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
