# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0017_auto_20161024_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'LocalProductGroups',
                'verbose_name': 'LocalProductGroup',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='localproductgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printaura.LocalProductGroup', verbose_name='Local Product Group'),
        ),
    ]
