# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0018_auto_20161024_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localproductgroup',
            options={'ordering': ['name'], 'verbose_name': 'Local Product Group', 'verbose_name_plural': 'Local Product Groups'},
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='brand/', verbose_name='Brand Logo', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_height',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_width',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='country/', verbose_name='Country Flag', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='country',
            name='image_height',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='image_width',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='local_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='local_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='local_sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='product/', verbose_name='Product Image', width_field='image_width'),
        ),
    ]
