# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printaura', '0019_auto_20161024_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='web_url',
            field=models.URLField(blank=True),
        ),
    ]
